# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            data dendrites
tagline:          'learning data science in Julia and Python'
description:      'learning data science using <a href="julialang.org" target="_blank">Julia</a> and Python'
url:              http://aflyax.github.io
baseurl:          /

author:
  name:           'Alexander Flyax'
  url:            https://twitter.com/aflyax

paginate:         5

# Custom vars
version:          7.7.0

github:
  repo:           https://github.com/aflyax
