name: '{data dendrites}'
url: 'http://127.0.0.1:4000/'
description: 'discovering data science with Julia and Python'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: redcarpet
excerpt_separator:  "<!--more-->"
redcarpet:
  extensions: ["no_intra_emphasis", "superscript", "footnotes", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

author: 'Alexander Flyax'
disqus_shortname: datadendrites
google_analytics: UA-6063059-2

sass:
    sass_dir: _sass
    style: :compressed
