name: '{data dendrites}'
# url: 'aflyax.github.io/'
description: 'exploring data science with Python et al.'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: redcarpet
excerpt_separator:  "<!--more-->"
redcarpet:
  extensions: ["no_intra_emphasis", "superscript", "footnotes", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

author: 'Alexander Flyax'
disqus_shortname: datadendrites
google_analytics: UA-6063059-2

paginate:            5

sass:
    sass_dir: _sass
    style: :compressed
