# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '{data dendrites}'
tagline:          'exploring data science in Julia and Python'
description:      'exploring data science using <a href="http://julialang.org" target="_blank">Julia</a> and <a href="http://nbviewer.ipython.org/github/gumption/Python_for_Data_Science/blob/master/Python_for_Data_Science_all.ipynb" target="_blank">Python</a>'
url:              http://aflyax.github.io
baseurl:          /

author:
  name:           'Alexander Flyax'
  url:            https://aflyax.github.io

paginate:         5

# Custom vars
version:          7.7.0

github:
  repo:           https://github.com/aflyax
